name: lab11

on:
  push:
    branches:
      - '**lab11**'
  pull_request:
    branches:
      - lab11

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

      fail-fast: false

    steps:

      - name: setup
        run: |
          echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head }}
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.head.user.login }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: dependency (ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          sudo apt update
          sudo apt install wget
          wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          sudo rm -rf /usr/bin/go
          sudo tar -C /usr/bin -xzf go1.17.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/bin/go/bin
          sudo apt-get -qy install python3
          sudo apt-get install python3 python3-pip python3-dev git libssl-dev libffi-dev build-essential
      - name: grade
        run: |
          export PATH=$PATH:/usr/bin/go/bin
          username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
          echo "cd lab11/$username"
          cd lab11/$username
          bash ../validate.sh
