name: lab9

on:
  push:
    branches:
      - '**lab9**'
  pull_request:
    branches:
      - lab9

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

      fail-fast: false

    steps:

      - name: setup
        run: |
          echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head }}
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.head.user.login }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: dependency (ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          go version
          whereis go
          sudo apt update
          sudo apt install wget
          echo "wget"
          wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          echo "rm"
          sudo rm -rf /usr/bin/go
          echo "tar"
          sudo tar -C /usr/bin -xzf go1.17.1.linux-amd64.tar.gz
          echo "export"
          export PATH=$PATH:/usr/bin/go/bin
          go version
          sudo apt-get -qy install python3
      - name: grade
        run: |
          username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
          echo "cd lab9/$username"
          cd lab9/$username
          bash ../validate.sh